# -*- coding: utf-8 -*-
"""Student_Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O2w-4N8UeS-wkJ4K5rkgR258udk5g4KL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

data  = pd.read_csv('student_performance__dataset.csv')

data

X = data.iloc[:,0:3].values

y = data.iloc[:,-1].values

X

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

X_train.shape

X_test.shape

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

y_pred

from sklearn.metrics import confusion_matrix,classification_report,ConfusionMatrixDisplay

print(confusion_matrix(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)

cm

disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=model.classes_)
disp.plot()
plt.grid(False)
plt.show()

print(classification_report(y_test,y_pred))

def f(Hours,Attendanc,Marks):
    return(model.predict(Hours,Attendance,Marks))

def predict_student(hours, attendance, marks):
    result = model.predict([[hours, attendance, marks]])
    return "Pass ✅" if result == 1 else "Fail ❌"

predict_student(6,85,75)

predict_student(4,50,59)



